# Generated by Django 5.2.4 on 2025-08-09 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default_img.jpg', null=True, upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participa', to=settings.AUTH_USER_MODEL),
        ),
    ]
